---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[drush::default]
    attributes:
  - name: git
    run_list:
      - recipe[git]
      - recipe[drush::default]
    attributes:
      drush:
        install_method: 'git'
        version: '6.x'
  - name: git-7
    run_list:
      - recipe[git]
      - recipe[drush::default]
    attributes:
      drush:
        install_method: 'git'
        version: 'master'
